### ISSUE TITLE
Add `--flightsql` paramter for `-c` and `-f`

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-dft#128]
Maybe it makes sense to also allow using the flightsql client when using `-c` and `-f`.  If so, we could add something like `--flightsql` for this.

**Comment by matthewmturner** [comment]
@alamb what do you think / would you find this useful?

**Comment by alamb** [comment]
I think this could be useful, depending on how we envision flightsql being used

If it is to have `dft` be a full on flightsql client, in addition to its other roles then it makes sense. Maybe we could  embed a full flightsql client, perhaps based on https://github.com/apache/arrow-rs/blob/master/arrow-flight/src/bin/flight_sql_client.rs in arrow-rs

Used like

```shell
dft flightsql -c 'show all' -h http://example.com/my_flightsql_service
```

The other thing we can do with flightsql is use it like a table provider

```sql
CREATE EXTERNAL TABLE flight_table AS FLIGHTSQL URL 'http://example.com/my_flightsql_service`;
SELECT * FROM flight_table
```

🤔

**Comment by matthewmturner** [comment]
@alamb ive actually already embedded the flightsql client. just needs to be run with `--features=flightsql` and there is a new flightsql tab (connection params are from config). i have some docs on it [here](https://github.com/datafusion-contrib/datafusion-tui?tab=readme-ov-file#flightsql---featuresflightsql)

**Comment by alamb** [comment]
Ah, got it - I see now how the config file would be useful 👍

**Comment by alamb** [comment]
🎉
