### ISSUE TITLE
Should we rename repo to `dft`?

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-dft#129]
There is now a scriptable CLI interface in addition to the tui application. I think the name `dft` could be more appropriate now that this is not just a tui.

**Comment by alamb** [comment]
Sounds good to me -- so would we call the repo to `datafusion-dft` ?

Or just `dft`?

**Comment by matthewmturner** [comment]
I was originally thinking just `dft` but i think to remain consistent with other repos in datafusion contrib and keep the association with `datafusion` obvious even outside the context of this organization its better to do `datafusion-dft`.  That being said, I don't have strong feelings on this point other than it should be renamed to `dft` so either works for me.

**Comment by alamb** [comment]
Let's try starting with `datafusion-dft` -- I did so -- and we can do more renaming later if needed

(I also added a branch protection to prevent me from accidentially pushing to the main branch -- we can adjust it if needed, I haven't really ever done this before so hopefully I did it correctly)
