### ISSUE TITLE
Querys that return large # of results can freeze / crash the app

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-dft#137]
I ran a query on local context that returned a large number of rows and the app became unresponsive after completing.  We need to paginate somehow

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/38b0ec03-db0f-4857-8288-e827708a0992">

**Comment by matthewmturner** [comment]
@alamb FYI pagination also relevant for local context

**Comment by alamb** [comment]
> @alamb FYI pagination also relevant for local context

I agree 

One way to do this might be to wrap the `SendableRecordBatchStream` in an object that buffers past results and fetches next result on demand. Something like this perhaps

```rust
struct @alamb FYI pagination also relevant for local context {
  // currently executing stream
  inner: SendableRecordBatchStream,
  // any batches that have been buffered so far
  batches: Vec<RecordBatch>,
  // current batch being shown
  current_batch: usize,
}

impl SendableRecordBatchStream {
  /// return the next batch in the stream
  async fn next(&self) -> &RecordBatch {
    self.current_batch += 1;
    self.current()
  }

  /// go to current_index
 async fn current(&self) -> &RecordBatch{
    while self.batches.len()+1 < current_batch {
      // fetch next batch from inner and put into self.batches
    }
    self.batches[self.current_batch]
}
```
