### ISSUE TITLE
Create / add duckdb metadata functions

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-dft#148]
Idea is to implement these metadata capabilities from [duckdb](https://duckdb.org/docs/data/parquet/metadata)

              I suggest we file a second ticket for implementing parquet_metadata and other duckdb metadata functions

_Originally posted by @alamb in https://github.com/datafusion-contrib/datafusion-dft/issues/125#issuecomment-2353468345_

Here is `parquet_metadata` implementation in datafusion-cli:

Implementation is here: https://github.com/apache/datafusion/blob/257e1409eca81cfff024ecc5e2567e9f67e6b5a3/datafusion-cli/src/functions.rs#L317-L459

I would like to suggest creating those functions in their own crate (perhaps datafusion-functions-parquet?) -- it could be in the datafusion-dft repo initially for convenience, but I think eventually the goal should be that dft just be focused on integration rather than actually implementing such features.

@matthewmturner  says:
>  i agree with putting it in its own crate. like @alamb said i also think that dft could be used as an incubator of sorts. For example I have taken that approach in my WASM function factory [PR](https://github.com/datafusion-contrib/datafusion-dft/pull/119/files). I have no intention of keeping that in this repo but its quite convenient for the time while it matures.

**Comment by alamb** [comment]
Updated the description a littlre

**Comment by devanbenz** [comment]
take

**Comment by matthewmturner** [comment]
Cross posting here as it relates to duckdb functions https://github.com/apache/datafusion/issues/12254

**Comment by matthewmturner** [comment]
hi @devanbenz just checking in on this - do you think youll have time to work on this? if not i can pick it up.

**Comment by matthewmturner** [comment]
i have started work on this
