### ISSUE TITLE
Example from README is not working

### ISSUE THREAD

**Issue by qrilka** [datafusion-contrib/datafusion-dft#188]
With `dft-0.1.0` installed as `cargo install datafusion-tui` I get the following error using the example in https://github.com/datafusion-contrib/datafusion-dft/blob/97a6c374d14c39616f0e461941c2cea277c46dc8/README.md#L90 
```
$ dft -c "SELECT 1+2"
error: Invalid value "SELECT 1+2" for '--batch-size <BATCH_SIZE>': Invalid batch size 'SELECT 1+2'

For more information try --help
```

**Comment by qrilka** [comment]
In `dft` help I see
```
OPTIONS:
    -c, --batch-size <BATCH_SIZE>    The batch size of each query, or use DataFusion default
```
so the error is probably expected but README needs a fix

**Comment by matthewmturner** [comment]
oh - definitely dont use version 0.1, that is very old.  i have not done a new release since starting work on the project again. right now just supports installs from source.  i hope to do another release in the coming month or so.

**Comment by qrilka** [comment]
Oh, right, github version works fine in this case.
But I found a thing which could be a problem, I tried this:
```
$ echo -e "id,name\n1,John\n2,Jane" > /tmp/test.csv
$ echo "create external table people stored as csv location '/tmp/test.csv';" > ~/.datafusion/.datafusionrc
```
and then `people` is not available in `dft` so I need to run `create` in SQL editor :-\

**Comment by matthewmturner** [comment]
Sigh, sorry i need to update that part of the README as well.  All configuration is now in `~/.config/dft` with the default DDL file being `~/.config/dft/ddl.sql`

It's explained [here](https://github.com/datafusion-contrib/datafusion-dft?tab=readme-ov-file#execution-config) but i need to update the other references as well.

**Comment by matthewmturner** [comment]
The project has been very fast moving since ive gotten back into it and i havent been as good as i need to be with updating the README as i should be. i had planned to do a full sweep at some point, but just havent gotten around to it yet.  Appreciate you raising these issues

**Comment by qrilka** [comment]
Thanks for your quick responses and this one looks to be resolved
