### ISSUE TITLE
Enable gsheet and excel querying 

### ISSUE THREAD

**Issue by turnebre** [datafusion-contrib/datafusion-dft#72]

**Comment by backkem** [comment]
ROAPI has a [GSheets source](https://github.com/roapi/roapi/blob/main/columnq/src/table/google_spreadsheets.rs). Maybe it could be made reusable as part of [datafusion-contrib/datafusion-table-providers](https://github.com/datafusion-contrib/datafusion-table-providers/).

**Comment by matthewmturner** [comment]
I am closing this for now as i dont see myself working on it for foreseeable future.  if its added to `datafusion-table-providers` it shouldnt be hard to add here
